//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace leliao.web.Models
{
    using System;
    using System.Collections.Generic;

    public partial class News : EntityCommon
    {
        public News()
        {
            //this.NewsComment = new HashSet<NewsComment>();
            //this.NewsShare = new HashSet<NewsShare>();
            //this.NewsPraise = new HashSet<NewsPraise>();
        }
        public Nullable<int> DissertationId { get; set; }

        //标题
        public string title { get; set; }
        //内容
        public string content { get; set; }
        //专题排序编号
        [DefaultValue(999)]
        public int topicOrder { get; set; }
        //访问量
        public int pv { get; set; }

        //是否在前段显示 0 不  1显示
        public int isActive { get; set; }
        //public virtual Dissertation Dissertation { get; set; }
        //public virtual ICollection<NewsPraise> NewsPraise { get; set; }
        //public virtual ICollection<NewsComment> NewsComment { get; set; }
        //public virtual ICollection<NewsShare> NewsShare { get; set; }
    }
}
